#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

pdflatex made-gecco2015.tex &&
pdflatex made-gecco2015.tex &&
pdflatex made-gecco2015.tex &&
bibtex made-gecco2015 &&
pdflatex made-gecco2015.tex &&
pdflatex made-gecco2015.tex &&
pdflatex made-gecco2015.tex &&
echo "-----------------------------" &&
pdflatex made-gecco2015.tex
#d2vips made.dvi -o && ps2pdf made.ps && echo " "
