#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

pdflatex made_tociaig.tex &&
pdflatex made_tociaig.tex &&
pdflatex made_tociaig.tex &&
bibtex made_tociaig &&
pdflatex made_tociaig.tex &&
pdflatex made_tociaig.tex &&
pdflatex made_tociaig.tex &&
echo "-----------------------------" &&
pdflatex made_tociaig.tex
#d2vips made.dvi -o && ps2pdf made.ps && echo " "
